language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script: 
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --dev --prefer-source

script: ./vendor/phpunit/phpunit/phpunit.php -c tests/complete.phpunit.xml
